# Generated by Django 6.0.2 on 2026-06-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exitems', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': True},
        ),
    ]
